"""initial schema

Revision ID: 8f50a6f0d3c8
Revises: 
Create Date: 2026-10-03 14:33:10.748574
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import store.timeutil


# revision identifiers, used by Alembic.
revision: str = '8f50a6f0d3c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_benchmark_symbol_date')
    )
    with op.batch_alter_table('benchmark_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_prices_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_prices_symbol'), ['symbol'], unique=False)

    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fx_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('base_ccy', sa.String(length=8), nullable=False),
    sa.Column('quote_ccy', sa.String(length=8), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('external_acc_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('trd_env', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_id', 'external_acc_id', 'trd_env', name='uq_account_identity')
    )
    op.create_table('strategy_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('trd_env', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('TESTING', 'LIVE', 'PAUSED', 'RETIRED', name='deploymentstatus'), nullable=False),
    sa.Column('allocated_capital', sa.Float(), nullable=False),
    sa.Column('reporting_ccy', sa.String(length=8), nullable=False),
    sa.Column('params_json', sa.String(length=2000), nullable=False),
    sa.Column('started_at', store.timeutil.UTCDateTime(length=32), nullable=True),
    sa.Column('ended_at', store.timeutil.UTCDateTime(length=32), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'trd_env', 'label', name='uq_deployment')
    )
    with op.batch_alter_table('strategy_deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_deployments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_deployments_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('kind', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='cashflowkind'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_flows_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('daily_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date_utc', sa.Date(), nullable=False),
    sa.Column('equity_open', sa.Float(), nullable=False),
    sa.Column('equity_close', sa.Float(), nullable=False),
    sa.Column('net_flow', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('pnl_nominal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'date_utc', name='uq_daily_return')
    )
    with op.batch_alter_table('daily_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_returns_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_returns_date_utc'), ['date_utc'], unique=False)

    op.create_table('deployment_equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('allocated_capital', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('win_rate', sa.Float(), nullable=False),
    sa.Column('reporting_ccy', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_equity_snapshots_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployment_equity_snapshots_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('equity_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('total_equity', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('net_flow_since_prev', sa.Float(), nullable=False),
    sa.Column('reporting_ccy', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_equity_snapshots_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_equity_snapshots_ts_utc'), ['ts_utc'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('ts_utc', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY', 'CASH', 'OPTION', 'CRYPTO', 'FUTURE', 'OTHER', name='assetclass'), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('last_price', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('unrealized_pl', sa.Float(), nullable=False),
    sa.Column('today_pl', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'symbol', name='uq_position_symbol')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_positions_symbol'), ['symbol'], unique=False)

    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', name='tradedirection'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='tradestatus'), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('closed_qty', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('entry_ts_utc', store.timeutil.UTCDateTime(length=32), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_ts_utc', store.timeutil.UTCDateTime(length=32), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('pnl_nominal', sa.Float(), nullable=True),
    sa.Column('pnl_pct', sa.Float(), nullable=True),
    sa.Column('commission_total', sa.Float(), nullable=False),
    sa.Column('tp_level', sa.Float(), nullable=True),
    sa.Column('sl_level', sa.Float(), nullable=True),
    sa.Column('order_type', sa.Enum('LIMIT', 'MARKET', name='ordertype'), nullable=True),
    sa.Column('meta_json', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trades_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trades_symbol'), ['symbol'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=True),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('broker_order_id', sa.String(length=64), nullable=False),
    sa.Column('ts_utc_created', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', 'SHORT_OPEN', 'SHORT_CLOSE', name='side'), nullable=False),
    sa.Column('order_type', sa.Enum('LIMIT', 'MARKET', name='ordertype'), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=False),
    sa.Column('tp_level', sa.Float(), nullable=True),
    sa.Column('sl_level', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'FILLED', 'PARTIAL', 'CANCELLED', 'REJECTED', name='orderstatus'), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['strategy_deployments.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'broker_order_id', name='uq_order_broker_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_broker_order_id'), ['broker_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_symbol'), ['symbol'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_trade_id'), ['trade_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_ts_utc_created'), ['ts_utc_created'], unique=False)

    op.create_table('snapshot_assetclass_comp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('asset_class', sa.Enum('EQUITY', 'CASH', 'OPTION', 'CRYPTO', 'FUTURE', 'OTHER', name='assetclass'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['equity_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_assetclass_comp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_assetclass_comp_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('snapshot_currency_comp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['equity_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshot_currency_comp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshot_currency_comp_snapshot_id'), ['snapshot_id'], unique=False)

    op.create_table('fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('broker_deal_id', sa.String(length=64), nullable=False),
    sa.Column('ts_utc', store.timeutil.UTCDateTime(length=32), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_deal_id', name='uq_fill_deal_id')
    )
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fills_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fills_ts_utc'), ['ts_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fills_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_fills_order_id'))

    op.drop_table('fills')
    with op.batch_alter_table('snapshot_currency_comp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_currency_comp_snapshot_id'))

    op.drop_table('snapshot_currency_comp')
    with op.batch_alter_table('snapshot_assetclass_comp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshot_assetclass_comp_snapshot_id'))

    op.drop_table('snapshot_assetclass_comp')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ts_utc_created'))
        batch_op.drop_index(batch_op.f('ix_orders_trade_id'))
        batch_op.drop_index(batch_op.f('ix_orders_symbol'))
        batch_op.drop_index(batch_op.f('ix_orders_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_orders_broker_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_account_id'))

    op.drop_table('orders')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trades_symbol'))
        batch_op.drop_index(batch_op.f('ix_trades_status'))
        batch_op.drop_index(batch_op.f('ix_trades_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_trades_account_id'))

    op.drop_table('trades')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_symbol'))
        batch_op.drop_index(batch_op.f('ix_positions_account_id'))

    op.drop_table('positions')
    with op.batch_alter_table('equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_equity_snapshots_account_id'))

    op.drop_table('equity_snapshots')
    with op.batch_alter_table('deployment_equity_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_equity_snapshots_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_deployment_equity_snapshots_deployment_id'))

    op.drop_table('deployment_equity_snapshots')
    with op.batch_alter_table('daily_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_returns_date_utc'))
        batch_op.drop_index(batch_op.f('ix_daily_returns_account_id'))

    op.drop_table('daily_returns')
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_ts_utc'))
        batch_op.drop_index(batch_op.f('ix_cash_flows_account_id'))

    op.drop_table('cash_flows')
    with op.batch_alter_table('strategy_deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_deployments_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_deployments_status'))

    op.drop_table('strategy_deployments')
    op.drop_table('accounts')
    op.drop_table('strategies')
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_ts_utc'))

    op.drop_table('fx_rates')
    op.drop_table('brokers')
    with op.batch_alter_table('benchmark_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_prices_symbol'))
        batch_op.drop_index(batch_op.f('ix_benchmark_prices_date'))

    op.drop_table('benchmark_prices')
    # ### end Alembic commands ###
